timeout: 10800s
options:
  substitution_option: ALLOW_LOOSE
  # Increase machine type for multi-arch builds.
  machineType: E2_HIGHCPU_32
steps:
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240523-a15ad90fc9
  entrypoint: bash
  env:
  - REGISTRY=gcr.io/k8s-staging-ingress-nginx
  args:
  - -c
  - gcloud auth configure-docker && cd images/nginx && make push
