name: Helm

on:
  push:
    branches:
      - main
      - release-*
  
  workflow_dispatch:

permissions:
  contents: read

jobs:

  changes:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files

    if: github.repository == 'kubernetes/ingress-nginx'

    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      charts: ${{ steps.filter.outputs.charts }}

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Lint chart
        run: |
          ct lint --config ./.ct.yaml --target-branch ${{ github.ref_name }}

          curl --silent --show-error --fail --location https://github.com/artifacthub/hub/releases/download/v1.17.0/ah_1.17.0_linux_amd64.tar.gz --remote-name
          echo "57c184b71a9a5c59192c2158fc08bdddca5c340fb1deeed0158383a665b38bf1  ah_1.17.0_linux_amd64.tar.gz" | shasum --check
          tar xzf ah_1.17.0_linux_amd64.tar.gz ah

          ./ah lint --path charts/ingress-nginx

          rm ah_1.17.0_linux_amd64.tar.gz ah

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/ingress-nginx/Chart.yaml'
              - 'charts/ingress-nginx/values.yaml'

  chart:
    name: Release Chart
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    needs:
      - changes

    if: ${{ needs.changes.outputs.charts == 'true' }}

    steps:
      - name: Checkout master
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0
          ref: ${{ github.ref_name }} 

      - name: Setup
        shell: bash
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584 # v1.6.0
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
        with:
          charts_dir: charts
